config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :airport_distances, except: [:show]
    resources :airports,          except: [:show]
    resources :alt_attributes,    except: [:show]
    resources :buying_guides,     except: [:show]
    resources :carousel_slides,   except: [:show] do
      member do
        post :move_down
        post :move_up
      end
    end
    resources :categories,        except: [:show]
    resources :countries,         except: [:show]
    resources :currencies,        except: [:show] do
      collection do
        get "update_exchange_rates"
      end
    end
    resources :coupons,           except: [:show]
    resources :footers,           except: [:show]
    resources :holiday_types,     except: [:show]
    resources :holiday_type_brochures, only: [:create, :destroy]
    resources :payments,          only: [:index, :show]
    resources :regions,           except: [:show] do
      member do
        get "edit_page"
      end
    end
    resources :resorts, except: [:show] do
      member do
        get "edit_page"
        post "destroy_directory_adverts"
        post "destroy_properties"
      end
    end
    resources :roles,             except: [:show]
    resources :snippets,          except: [:show]
    resources :tracked_actions, only: [:index]
    resources :trip_advisor_locations, only: [:index, :show, :update]

    resources :users, only: [:index, :destroy] do
      member do
        post "extend_windows"
      end
    end

    resources :window_base_prices, except: [:show]
  end

  resources :buying_guides, only: [:show]

  get "late-availability" => "late_availability#index"

  get "properties/search" => "properties#quick_search"

  resources :property_sales, only: [:index]

  get "resorts/:resort_slug/properties/rent" => "properties#browse_for_rent", :as => :resort_property_rent
  get "resorts/:resort_slug/properties/sale" => "properties#browse_for_sale", :as => :resort_property_sale
  get "resorts/:resort_slug/properties/new-developments" => "properties#new_developments",
      :as => :resort_property_new_developments

  get "regions/:region_slug/properties/rent" => "properties#browse_for_rent", :as => :region_property_rent
  get "regions/:region_slug/properties/sale" => "properties#browse_for_sale", :as => :region_property_sale
  get "regions/:region_slug/properties/new-developments" => "properties#new_developments", :as => :region_property_new_developments

  get "resorts/:id/resort-guide" => "resorts#resort_guide", :as => :resort_guide
  get "resorts/:id/ski-and-guiding-schools" => "resorts#ski_and_guiding_schools", :as => :ski_and_guiding_schools
  get "resorts/:id/summer-holidays" => "resorts#summer_holidays", :as => :summer_holidays
  get "resorts/:id/how-to-get-there" => "resorts#how_to_get_there", :as => :how_to_get_there
  resources :resorts, only: [:show] do
    get "featured", on: :collection
    member do
      get "resort-guide", action: "resort_guide"
      get "directory"
      get "feature"
      get "gallery"
      get "piste_map"
      get "piste_map_full_size"
    end
  end

  resources :airport_transfers do
    collection do
      get "find"
      post "results"
      get "skilifts"
    end
  end

  get "tools/rental-prices" => "rental_prices#index"
  get "tools/rental-prices/results" => "rental_prices#results"

  get "categories/:id/:resort_slug" => "categories#show", :as => :show_category

  get "sign_in" => "sessions#new"
  get "sign_out" => "sessions#destroy"
  get "sign_up" => "users#new"
  get "switch_user/:user_id" => "sessions#switch_user", :as => :switch_user
  resources :sessions

  get "advertise" => "users#show"
  get "first_advert" => "users#first_advert"
  get "my/details" => "users#edit", :as => :my_details
  resources :users, except: [:index, :destroy] do
    collection do
      get "forgot_password"
      post "forgot_password_change"
      get "forgot_password_new"
      post "forgot_password_send"
      get "select_role"
    end
  end

  resources :holiday_types, only: [:show], path: "holidays"

  get(
    ":place_type/:place_slug/holidays/:holiday_type_slug/(*tab)" =>
      "holiday_type_brochures#show",
    :as => :holiday_type_brochure,
    :constraints => {place_type: /countries|regions|resorts/}
  )

  resources :adverts do
    collection do
      post "update_basket_contents"
      get  "place_order"
      post "add_windows_to_basket"
      get  "buy_windows"
      post "delete_all_new_advertisables"
    end
  end
  get "my/adverts" => "adverts#my", :as => :my_adverts

  resources :properties do
    member do
      post "advertise_now"
      get "choose_window"
      get  "contact"
      get  "interhome_booking_form"
      post "place_in_window"
      post "remove_from_window"
    end

    collection do
      get  "rent"
      get  "sale"
      get  "current_time"

      post "interhome_enquiry"
      post "check_interhome_booking"
      get "update_booking_durations_select"
      get "update_day_of_month_select"
      get "interhome_payment_success"
      get "interhome_payment_failure"
    end
  end

  get "accommodation/:permalink" => "properties#show_interhome", :as => :interhome_property

  resources :property_base_prices

  post "property_importer/import"
  get  "property_importer/import_documentation"
  get  "property_importer/new_import"
  get  "property_importer/new_pericles_import"
  post "property_importer/pericles_import"

  resources :property_volume_discounts

  resources :directory_adverts do
    member do
      post "advertise_now"
      post "click"
    end
  end

  resources :enquiries do
    collection do
      get "current_time"
      get "my"
    end
  end

  resources :interhome_place_resorts

  resources :images

  get "basket" => "adverts#basket"

  resources :orders do
    collection do
      get "latest_receipt"
      get "receipts"
      get "select_payment_method"
    end
    member do
      get "invoice"
      get "receipt"
    end
  end

  resources :payments do
    get  "complete_payment_not_required", on: :collection
    post "worldpay_callback", on: :collection
  end

  resources :regions, only: [:show]
  get "regions/:id/how-to-get-there" => "regions#how_to_get_there", :as => :how_to_get_to_region
  get "regions/:id/piste_map" => "regions#piste_map", :as => :region_piste_map

  get "welcome/:role" => "roles#sales_pitch", :as => :sales_pitch

  resources :trip_advisor_properties, only: [] do
    post "get_details", on: :member
  end

  resources :websites
  get "cms/directory-price" => "websites#edit_prices", :as => :directory_price

  resources :pages do
    get "copy", on: :member
  end

  get "cms" => "cms#index"
  get "guide" => "cms#guide"
  get "management_information" => "cms#management_information"
  get "gross_sales_analysis" => "cms#gross_sales_analysis"

  get "export" => "export#index"
  get "export/spreadsheet/:class_name" => "export#spreadsheet", :as => :export_spreadsheet

  get "contact" => "home#contact"
  get "privacy" => "home#privacy"
  get "style-guide" => "home#style_guide", :as => :style_guide
  get "terms" => "home#terms"
  get "sitemap.xml" => "application#sitemap", :as => "sitemap", :format => "xml"
  get "restart" => "application#restart", :as => "restart"
  get "precompile_assets" => "application#precompile_assets", :as => "precompile_assets"

  get "search" => "search#index"
  get "search/place_names" => "search#place_names"

  get "home/search" => "home#search", :as => :home_search
  get "home/search_sales" => "home#search_sales", :as => :home_search_sales

  get "home/country_options_for_quick_search" => "home#country_options_for_quick_search"
  get "home/resort_options_for_quick_search" => "home#resort_options_for_quick_search"
  root "home#index"

  get "*a", to: "application#routing_error"
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController
  before_action :admin_required

  layout "admin"

  def index
    @heading_a = t("cms_controller.cms")
    default_page_title(@heading_a)
  end

  def guide
    @heading_a = t("cms_controller.guide")
    default_page_title(@heading_a)
  end

  def management_information
    @heading_a = t("cms_controller.management_information")
    default_page_title(@heading_a)
  end

  def gross_sales_analysis
    @heading_a = t("cms_controller.gross_sales_analysis")
    default_page_title(@heading_a)
  end
end

app/views/cms/gross_sales_analysis.html.erb
<table class="table table-bordered table-striped">
  <tr>
    <th>Country</th>
    <th>€ Properties Rent</th>
    <th>€ Properties Sale</th>
    <th>€ Directory Adverts</th>
    <th>€ Total Revenue</th>
    <th># Properties Rent</th>
    <th># Properties Sale</th>
    <th># Directory Adverts</th>
    <th># Banner Adverts</th>
  </tr>
<% Country.with_resorts.each do |c| %>
  <tr>
    <th><%= c.name %></th>
    <td><%= euros_from_cents(c.gross_revenue_rentals_ytd) %></td>
    <td><%= euros_from_cents(c.gross_revenue_sales_ytd) %></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><%= c.count_rentals_ytd %></td>
    <td><%= c.count_sales_ytd %></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
<% end %>
</table>

app/views/cms/guide.html.erb
<h2>Contents</h2>
<ul>
  <li><a href="#guide-sftp-access">SFTP Access</a></li>
  <li><a href="#guide_directory_adverts">Directory Adverts</a></li>
  <li><a href="#guide-seo-meta-defaults">SEO Meta Defaults</a></li>
</ul>

<h3 id="guide-sftp-access">SFTP Access</h3>

<p>
  The SFTP access details are:
</p>

<p>
  Host: straylight.yesl.co.uk<br>
  Username: mychaletfinder<br>
  Password: KLqxdGqP99
</p>

<p>
  You will need to connect in SFTP mode and not FTP.
</p>

<h3 id="guide_directory_adverts">Directory Adverts</h3>

<p>
  This guide shows how you can add directory adverts that aren't associated with a particular user.
</p>

<ol>
  <li>Log in as an administrator</li>
  <li>Ensure the administrator has a valid promotion code for free directory adverts</li>
  <li>Click Account from the top menu</li>
  <li>Click New Directory Advert</li>
  <li>Enter the directory advert details</li>
  <li>Press Save</li>
  <li>Press your browser's back button and enter another directory advert if you want to</li>
  <li>Checkout</li>
</ol>

<h3 id="guide-seo-meta-defaults">SEO Meta Defaults</h3>

<p>
  These can be changed in the YAML locale (translation) files under
  <kbd>config/locales/</kbd>. The files are de.yml (German),
  en.yml (English), fr.yml (French) and it.yml (Italian).
</p>

<p>
  The files should be edited in a proper text editor and saved as UTF-8.
  The files should be uploaded to the server with UNIX line endings (setting
  your FTP client to ASCII mode should do this).
</p>

<p>
  After making changes you should restart the application for the changes to
  take effect. You should also let Ian ianfleeton+mychaletfinder@gmail.com know
  so that your changes do not get overwritten.
</p>

<p>
  The following keys can be set:
</p>

<ul>
  <li>properties_controller.meta_descriptions.show</li>
  <li>properties_controller.meta_descriptions.show_interhome</li>
  <li>properties.titles.browse_for_rent</li>
  <li>properties.titles.browse_for_sale</li>
  <li>properties.titles.new</li>
  <li>properties.titles.new_developments</li>
  <li>properties.titles.show</li>
  <li>resorts_controller.meta_descriptions.directory</li>
  <li>resorts_controller.meta_descriptions.gallery</li>
  <li>resorts_controller.meta_descriptions.piste_map</li>
  <li>resorts_controller.meta_descriptions.resort_guide</li>
  <li>resorts_controller.meta_descriptions.show</li>
  <li>resorts_controller.meta_descriptions.summer_holidays</li>
  <li>resorts_controller.titles.directory</li>
  <li>resorts_controller.titles.gallery</li>
  <li>resorts_controller.titles.piste_map</li>
  <li>resorts_controller.titles.resort_guide</li>
  <li>resorts_controller.titles.show</li>
  <li>resorts_controller.titles.summer_holidays</li>
</ul>

<p>
  You can use the following placeholders in certain strings:
</p>

<ul>
  <li>%{country}</li>
  <li>%{property_name}</li>
  <li>%{rent_or_sale}</li>
  <li>%{resort}</li>
  <li>%{strapline}</li>
</p>

app/views/cms/index.html.slim
= page_header 'CMS'
p= "There are #{pluralize(delayed_job_workers, 'delayed_job worker')} running. There should be at least 4."
p= link_to t('.restart'), restart_path, class: 'btn btn-secondary'
p= link_to 'Precompile Assets', precompile_assets_path, class: 'btn btn-secondary'
p= link_to 'Style Guide', style_guide_path, class: 'btn btn-secondary'

app/views/cms/management_information.html.erb
<a href="<%= gross_sales_analysis_path %>">
  <h2>Gross Sales Analysis</h2>
  <p>By country and resort.</p>
</a>