config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :airport_distances, except: [:show]
    resources :airports,          except: [:show]
    resources :alt_attributes,    except: [:show]
    resources :buying_guides,     except: [:show]
    resources :carousel_slides,   except: [:show] do
      member do
        post :move_down
        post :move_up
      end
    end
    resources :categories,        except: [:show]
    resources :countries,         except: [:show]
    resources :currencies,        except: [:show] do
      collection do
        get "update_exchange_rates"
      end
    end
    resources :coupons,           except: [:show]
    resources :footers,           except: [:show]
    resources :holiday_types,     except: [:show]
    resources :holiday_type_brochures, only: [:create, :destroy]
    resources :payments,          only: [:index, :show]
    resources :regions,           except: [:show] do
      member do
        get "edit_page"
      end
    end
    resources :resorts, except: [:show] do
      member do
        get "edit_page"
        post "destroy_directory_adverts"
        post "destroy_properties"
      end
    end
    resources :roles,             except: [:show]
    resources :snippets,          except: [:show]
    resources :tracked_actions, only: [:index]
    resources :trip_advisor_locations, only: [:index, :show, :update]

    resources :users, only: [:index, :destroy] do
      member do
        post "extend_windows"
      end
    end

    resources :window_base_prices, except: [:show]
  end

  resources :buying_guides, only: [:show]

  get "late-availability" => "late_availability#index"

  get "properties/search" => "properties#quick_search"

  resources :property_sales, only: [:index]

  get "resorts/:resort_slug/properties/rent" => "properties#browse_for_rent", :as => :resort_property_rent
  get "resorts/:resort_slug/properties/sale" => "properties#browse_for_sale", :as => :resort_property_sale
  get "resorts/:resort_slug/properties/new-developments" => "properties#new_developments",
      :as => :resort_property_new_developments

  get "regions/:region_slug/properties/rent" => "properties#browse_for_rent", :as => :region_property_rent
  get "regions/:region_slug/properties/sale" => "properties#browse_for_sale", :as => :region_property_sale
  get "regions/:region_slug/properties/new-developments" => "properties#new_developments", :as => :region_property_new_developments

  get "resorts/:id/resort-guide" => "resorts#resort_guide", :as => :resort_guide
  get "resorts/:id/ski-and-guiding-schools" => "resorts#ski_and_guiding_schools", :as => :ski_and_guiding_schools
  get "resorts/:id/summer-holidays" => "resorts#summer_holidays", :as => :summer_holidays
  get "resorts/:id/how-to-get-there" => "resorts#how_to_get_there", :as => :how_to_get_there
  resources :resorts, only: [:show] do
    get "featured", on: :collection
    member do
      get "resort-guide", action: "resort_guide"
      get "directory"
      get "feature"
      get "gallery"
      get "piste_map"
      get "piste_map_full_size"
    end
  end

  resources :airport_transfers do
    collection do
      get "find"
      post "results"
      get "skilifts"
    end
  end

  get "tools/rental-prices" => "rental_prices#index"
  get "tools/rental-prices/results" => "rental_prices#results"

  get "categories/:id/:resort_slug" => "categories#show", :as => :show_category

  get "sign_in" => "sessions#new"
  get "sign_out" => "sessions#destroy"
  get "sign_up" => "users#new"
  get "switch_user/:user_id" => "sessions#switch_user", :as => :switch_user
  resources :sessions

  get "advertise" => "users#show"
  get "first_advert" => "users#first_advert"
  get "my/details" => "users#edit", :as => :my_details
  resources :users, except: [:index, :destroy] do
    collection do
      get "forgot_password"
      post "forgot_password_change"
      get "forgot_password_new"
      post "forgot_password_send"
      get "select_role"
    end
  end

  resources :holiday_types, only: [:show], path: "holidays"

  get(
    ":place_type/:place_slug/holidays/:holiday_type_slug/(*tab)" =>
      "holiday_type_brochures#show",
    :as => :holiday_type_brochure,
    :constraints => {place_type: /countries|regions|resorts/}
  )

  resources :adverts do
    collection do
      post "update_basket_contents"
      get  "place_order"
      post "add_windows_to_basket"
      get  "buy_windows"
      post "delete_all_new_advertisables"
    end
  end
  get "my/adverts" => "adverts#my", :as => :my_adverts

  resources :properties do
    member do
      post "advertise_now"
      get "choose_window"
      get  "contact"
      get  "interhome_booking_form"
      post "place_in_window"
      post "remove_from_window"
    end

    collection do
      get  "rent"
      get  "sale"
      get  "current_time"

      post "interhome_enquiry"
      post "check_interhome_booking"
      get "update_booking_durations_select"
      get "update_day_of_month_select"
      get "interhome_payment_success"
      get "interhome_payment_failure"
    end
  end

  get "accommodation/:permalink" => "properties#show_interhome", :as => :interhome_property

  resources :property_base_prices

  post "property_importer/import"
  get  "property_importer/import_documentation"
  get  "property_importer/new_import"
  get  "property_importer/new_pericles_import"
  post "property_importer/pericles_import"

  resources :property_volume_discounts

  resources :directory_adverts do
    member do
      post "advertise_now"
      post "click"
    end
  end

  resources :enquiries do
    collection do
      get "current_time"
      get "my"
    end
  end

  resources :interhome_place_resorts

  resources :images

  get "basket" => "adverts#basket"

  resources :orders do
    collection do
      get "latest_receipt"
      get "receipts"
      get "select_payment_method"
    end
    member do
      get "invoice"
      get "receipt"
    end
  end

  resources :payments do
    get  "complete_payment_not_required", on: :collection
    post "worldpay_callback", on: :collection
  end

  resources :regions, only: [:show]
  get "regions/:id/how-to-get-there" => "regions#how_to_get_there", :as => :how_to_get_to_region
  get "regions/:id/piste_map" => "regions#piste_map", :as => :region_piste_map

  get "welcome/:role" => "roles#sales_pitch", :as => :sales_pitch

  resources :trip_advisor_properties, only: [] do
    post "get_details", on: :member
  end

  resources :websites
  get "cms/directory-price" => "websites#edit_prices", :as => :directory_price

  resources :pages do
    get "copy", on: :member
  end

  get "cms" => "cms#index"
  get "guide" => "cms#guide"
  get "management_information" => "cms#management_information"
  get "gross_sales_analysis" => "cms#gross_sales_analysis"

  get "export" => "export#index"
  get "export/spreadsheet/:class_name" => "export#spreadsheet", :as => :export_spreadsheet

  get "contact" => "home#contact"
  get "privacy" => "home#privacy"
  get "style-guide" => "home#style_guide", :as => :style_guide
  get "terms" => "home#terms"
  get "sitemap.xml" => "application#sitemap", :as => "sitemap", :format => "xml"
  get "restart" => "application#restart", :as => "restart"
  get "precompile_assets" => "application#precompile_assets", :as => "precompile_assets"

  get "search" => "search#index"
  get "search/place_names" => "search#place_names"

  get "home/search" => "home#search", :as => :home_search
  get "home/search_sales" => "home#search_sales", :as => :home_search_sales

  get "home/country_options_for_quick_search" => "home#country_options_for_quick_search"
  get "home/resort_options_for_quick_search" => "home#resort_options_for_quick_search"
  root "home#index"

  get "*a", to: "application#routing_error"
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :set_resort_and_region_from_place_name,
    only: %i[search search_sales]

  def index
    @featured_properties = @w.featured_properties
  end

  def search
    if @resort
      start_date = params[:start_date].present? ? params[:start_date].to_date.strftime("%Y.%m.%d") : nil
      end_date = params[:end_date].present? ? params[:end_date].to_date.strftime("%Y.%m.%d") : nil
      redirect_to resort_property_rent_path(@resort, start_date: start_date, end_date: end_date, bedrooms: params[:bedrooms], sleeps: params[:sleeps])
    elsif @region
      redirect_to region_property_rent_path(@region)
    # elsif @country
    #   redirect_to
    else
      redirect_to root_path
    end
  end

  def search_sales
    if @resort
      redirect_to resort_property_sale_path(@resort)
    elsif @region
      redirect_to region_property_sale_path(@region)
    else
      redirect_to root_path
    end
  end

  def country_options_for_quick_search
    @countries = if params[:holiday_type_id].blank?
      []
    else
      HolidayType.find(params[:holiday_type_id]).visible_country_brochures.map { |b| b.brochurable }
    end
    render layout: false
  end

  # Despite the name, this action populates @resorts with both Regions and
  # Resorts.
  def resort_options_for_quick_search
    if params[:country_id].blank?
      @resorts = []
    else
      country = Country.find(params[:country_id])
      @resorts = if params[:holiday_type_id].blank?
        country.visible_regions + country.visible_resorts
      else
        country.region_brochures(params[:holiday_type_id]).map { |b| b.brochurable } + country.resort_brochures(params[:holiday_type_id]).map { |b| b.brochurable }
      end
    end
    render layout: false
  end

  def contact
    default_page_title t("contact")
  end

  def privacy
    default_page_title t("privacy")
  end

  def terms
    default_page_title t("terms")
  end

  private

  def set_resort_and_region_from_place_name
    if params[:place_name]
      @resort ||= Resort.find_by(name: params[:place_name])
      @region ||= Region.find_by(name: params[:place_name])
      @country ||= Country.find_by(name: params[:place_name])
    end
  end
end

app/views/home/_carousel_slide.html.slim
li
  a href="#{carousel_slide.link}"
    = image_tag(carousel_slide.image_url, alt: carousel_slide.alt)
    .caption
      = raw carousel_slide.caption
      = image_tag 'slider-arrow.png', alt: '', style: 'display:inline-block;'

app/views/home/_date_range_picker.html.erb
<label>Check in - Check out</label>
<div id="check_in_out" class="date-range-pick">
    <i class="far fa-calendar"></i>
    <span> Check in - Check out</span>
</div>
<input id="check_in" name="start_date" style="display: none">
<input id="check_out" name="end_date" style="display: none">

<script>
    $(function () {
        <% if start_date.present? && end_date.present? %>
            $('#check_in').val("<%= start_date %>");
            $('#check_out').val("<%= end_date %>");
            $('#check_in_out span').html("<%= Date.parse(start_date).strftime("%d %b %Y") %>" + ' - ' + "<%= Date.parse(end_date).strftime("%d %b %Y") %>");
            $('#check_in_out span').css('color', 'black');
        <% else %>
            $('#check_in').val(null);
            $('#check_out').val(null);
        <% end %>
    });

    $('#check_in_out').daterangepicker({
        "autoApply": true,
        "opens": "center",
        "linkedCalendars": false
    }, function(start, end, label) {
        const monthNames = ["Jan", "Feb", "Mar", "Apr", "May","Jun","Jul", "Aug", "Sepr", "Oct", "Nov","Dec"]
        const format = (date) => {
            const new_date = date.format('DD B YYYY');
            const month = monthNames[Number(date.format('MM')) - 1];
            return new_date.replace('B', month);
        }

        $('#check_in_out span').html(format(start) + ' - ' + format(end));
        $('#check_in_out span').css('color', 'black');
        $('#check_in').val(start);
        $('#check_out').val(end);
    });
</script>

app/views/home/_datepickers.html.slim
javascript:
  $(function() {
    $('.home-datepicker input').pickadate({
      onOpen: function() {
        console.log('Opened up');
        if($('.home-datepicker .help').length == 0) {
          $('.home-datepicker .picker__footer').after('<p class="help">#{t('.help')}</p>');
        }
      }
    });
  });
.search-field
  label for="start_date" Check-In
  .search-field-input
    .date#arrival-datepicker.home-datepicker
      input#start_date type="text" value="#{params[:start_date] ? params[:start_date] : t('.check_in_date')}" name="start_date"
.search-field
  label for="end_date" Check-Out
  .search-field-input
    .date#departure-datepicker.home-datepicker
      input.form-control type="text" value="#{params[:end_date] ? params[:end_date] : t('.check_out_date')}" name="end_date"

app/views/home/_home_search.html.erb
<div id="bloodhound">
  <form class="search-form cf" action="<%= home_search_path %>">
    <div class="search-field search-field-destination">
      <label for="destination">Destination</label>
      <input id="destination" class="typeahead" type="text" placeholder="Find rentals here" name="place_name" value="<%= @destination %>">
    </div>
    <div class="search-field search-field-checkin-checkout">
      <%= render 'home/date_range_picker', start_date: '', end_date: '' %>
    </div>
    <div class="search-field search-field-bedrooms">
      <label for="search_bedrooms">Bedrooms</label>
      <select name="bedrooms">
        <option value="">Choose</option>
        <% (1..20).each do |i| %>
          <option value="<%= i %>"><%= i %></option>
        <% end %>
      </select>
    </div>
    <div class="search-field search-field-sleeps">
      <label for="search_sleeps">Sleeps</label>
      <select name="sleeps">
        <option value="">Choose</option>
        <% (1..40).each do |i| %>
          <option value="<%= i %>"><%= i %></option>
        <% end %>
      </select>
    </div>
    <div class="search-field search-field-submit">
      <input class="button action-button form-control" type="submit" value="Search">
    </div>
  </form>
</div>

<script>
  $('.search-form').on('submit', () => {
    const placeName = $('.tt-input').val();

    if(placeName) {
      return true;
    } else {
      alert('Please select a destination');
    }

    return false;
  });

  // constructs the suggestion engine
  const places = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    prefetch: '/search/place_names.json'
  });

  places.clearPrefetchCache();

  $('#bloodhound .typeahead').typeahead({
    hint: true,
    highlight: true
  }, {
    name: 'places',
    source: places,
    display: 'name',
    limit: 15,
    templates: {
      suggestion: (data) => {
         return '<div>' + data.name + ' <div class="property-count">' + data.count + ' <div>For Rent</div></div></div>';
      }
    }
  }).keypress((e) => {
    if (e.which == 13) {
      $('.tt-suggestion:first-child').trigger('click');
    }
  });

  $(() => {
    $('.search-datepicker input').pickadate({
      format: 'd mmm, yyyy'
    });

    $('#destination').val("<%= @destination %>");
  });
</script>

app/views/home/_quick_search.html.slim
section
  #quick-search
    = form_tag({controller: 'properties', action: 'quick_search'}, method: 'get') do
      h5 style="margin-top: 0; margin-bottom: 0;" = t('.heading')
      .search-form
        .search-field
          label for="holiday_type_id" Holiday
          .search-field-input
            select#holiday_type_id.form-control name="holiday_type_id"
              option value=""= t('.choose')
              = options_for_select(HolidayType.on_menu.map {|ht| [ht, ht.id]})
        .search-field
          label for="country_id" Country
          .search-field-input
            select#country_id.form-control name="country_id"
              option value=""= t('.choose')
              option value=""= t('.choose_holiday_first')
        .search-field
          label for="resort_id" Resort
          .search-field-input
            select#resort_id.form-control name="resort_slug"
              option value=""= t('.choose')
              option value=""= t('.choose_country_first')
        .search-field
          = render 'properties/sleeps_select'
        = render 'properties/price_range_select'
        .search-field.search-field-checkin-checkout
          = render 'home/date_range_picker', start_date: '', end_date: ''
        .search-field-submit
          input type="submit" value="#{t('.search')}" class="button action-button"

app/views/home/_top_countries_and_resorts.html.erb
  <% Country.all(limit: 6, order: 'property_count DESC').each do |country| %>
  <div class="country">
    <h2><%= country %></h2>
    <% Resort.all(limit: 3, order: 'property_count DESC', conditions: { country_id: country.id }).each do |resort| %>
    <div class="resort">
      <h3><%= link_to resort, resort %></h3>
      <p>
        <%= link_to "Accommodation to rent in #{resort}", resort_property_rent_path(resort) %><br>
        <%= link_to "Accommodation for sale in #{resort}", resort_property_sale_path(resort) %><br>
      </p>
    </div>
    <% end %>
  </div>
  <% end %>

app/views/home/contact.html.erb
<%= raw @w.contact_details %>

app/views/home/country_options_for_quick_search.html.slim
select#country_id.form-control name="country_id"
  option value=""= t('home.quick_search.choose_country')
  - if @countries.empty?
    option value=""= t('home.quick_search.choose_holiday_first')
  - else
    = options_for_select @countries.map { |c| [c, c.id] }
select#resort_id.form-control name="resort_slug"
  option value=""= t('home.quick_search.choose_resort')
  option value=""= t('home.quick_search.choose_country_first')

app/views/home/index.html.slim
- content_for :search do
  = render 'home_search'


= content_for :carousel do
  ul#carousel-slides
    = render partial: 'carousel_slide', collection: CarouselSlide.active.order(:position)

= content_for :custom_footer do
  = raw @footer_box

- cache [@w, Date.today] do
  = raw Liquid::Template.parse(@w.home_content).render('featured_properties' => render('shared/featured_properties'))

app/views/home/privacy.html.erb
<%= raw @w.privacy_policy %>

app/views/home/resort_options_for_quick_search.html.slim
select#resort_id.form-control name="resort_slug"
  option value=""= t('home.quick_search.choose_resort')
  - if @resorts.empty?
    option value=""= t('home.quick_search.choose_country_first')
  - else
    = options_for_select @resorts.map { |r| [r, r.slug] }

app/views/home/terms.html.slim
= content_for :title, t('.title')

= content_for :breadcrumbs_and_heading, breadcrumbs_and_heading({t('home_page') => root_path}, t('.heading'))

= raw @w.terms